2025-02-28 20:53:22.979 [main] INFO  ad.hibernate.hmarort.Main - Iniciando aplicación de gestión de pedidos
2025-02-28 20:53:22.982 [main] INFO  ad.hibernate.hmarort.Main - Interfaz seleccionada: automatica
2025-02-28 20:53:22.999 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2025-02-28 20:53:23.120 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@176b75f7
2025-02-28 20:53:23.122 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2025-02-28 20:53:23.122 [main] INFO  a.h.h.database_config.SQLiteConfig - Iniciando inicialización de base de datos SQLite
2025-02-28 20:53:23.141 [main] WARN  a.h.h.database_config.SQLiteConfig - Advertencia al ejecutar statement: [SQLITE_ERROR] SQL error or missing database (table Zonas_Envio already exists)
2025-02-28 20:53:23.141 [main] WARN  a.h.h.database_config.SQLiteConfig - Advertencia al ejecutar statement: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: Zonas_Envio.id_zona)
2025-02-28 20:53:23.141 [main] WARN  a.h.h.database_config.SQLiteConfig - Advertencia al ejecutar statement: [SQLITE_CONSTRAINT_PRIMARYKEY] A PRIMARY KEY constraint failed (UNIQUE constraint failed: Clientes.id_cliente)
2025-02-28 20:53:23.141 [main] INFO  a.h.h.database_config.SQLiteConfig - Base de datos inicializada correctamente
2025-02-28 20:53:23.146 [main] INFO  a.h.hmarort.utils.SessionManager - Inicializando SessionFactory de Hibernate
2025-02-28 20:53:23.220 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 6.4.1.Final
2025-02-28 20:53:23.428 [main] INFO  o.h.c.i.RegionFactoryInitiator - HHH000026: Second-level cache disabled
2025-02-28 20:53:23.507 [main] WARN  o.hibernate.orm.connections.pooling - HHH10001002: Using built-in connection pool (not intended for production use)
2025-02-28 20:53:23.507 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001005: Loaded JDBC driver class: org.sqlite.JDBC
2025-02-28 20:53:23.507 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001012: Connecting with JDBC URL [jdbc:sqlite:src/main/resources/pedidos.db]
2025-02-28 20:53:23.508 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001001: Connection properties: {}
2025-02-28 20:53:23.508 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001003: Autocommit mode: false
2025-02-28 20:53:23.510 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001115: Connection pool size: 20 (min=1)
2025-02-28 20:53:24.370 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2025-02-28 20:53:24.393 [main] INFO  o.hibernate.orm.connections.access - HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@404ced67] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode.
2025-02-28 20:53:24.404 [main] INFO  a.h.hmarort.utils.SessionManager - SessionFactory inicializada correctamente
2025-02-28 20:53:24.409 [main] INFO  a.h.hmarort.factory.DAOFactory - DAOFactory inicializado correctamente
2025-02-28 20:53:24.409 [main] INFO  ad.hibernate.hmarort.ui.UIAutoImpl - [GENERACIÓN AUTOMÁTICA DE DATOS]
2025-02-28 20:53:24.483 [main] INFO  a.h.h.d.i.DAOZonaEnvioImpl - Zona de envío insertada con ID: 3
2025-02-28 20:53:24.495 [main] INFO  a.h.h.d.i.DAOZonaEnvioImpl - Zona de envío insertada con ID: 4
2025-02-28 20:53:24.500 [main] INFO  a.h.h.d.i.DAOZonaEnvioImpl - Zona de envío insertada con ID: 5
2025-02-28 20:53:24.501 [main] INFO  ad.hibernate.hmarort.ui.UIAutoImpl - ✓ Zonas de envío generadas
2025-02-28 20:53:24.507 [main] INFO  a.h.h.d.i.DAOClienteImpl - Cliente insertado con ID: 5
2025-02-28 20:53:24.511 [main] INFO  a.h.h.d.i.DAOClienteImpl - Cliente insertado con ID: 6
2025-02-28 20:53:24.515 [main] INFO  a.h.h.d.i.DAOClienteImpl - Cliente insertado con ID: 7
2025-02-28 20:53:24.518 [main] INFO  a.h.h.d.i.DAOClienteImpl - Cliente insertado con ID: 8
2025-02-28 20:53:24.520 [main] INFO  a.h.h.d.i.DAOClienteImpl - Cliente insertado con ID: 9
2025-02-28 20:53:24.523 [main] INFO  ad.hibernate.hmarort.ui.UIAutoImpl - ✓ Clientes generados
2025-02-28 20:53:24.526 [main] INFO  a.h.h.d.implementacion.DAOPedidoImpl - Pedido insertado con ID: 1
2025-02-28 20:53:24.529 [main] INFO  a.h.h.d.implementacion.DAOPedidoImpl - Pedido insertado con ID: 2
2025-02-28 20:53:24.533 [main] INFO  a.h.h.d.implementacion.DAOPedidoImpl - Pedido insertado con ID: 3
2025-02-28 20:53:24.540 [main] INFO  a.h.h.d.implementacion.DAOPedidoImpl - Pedido insertado con ID: 4
2025-02-28 20:53:24.546 [main] INFO  a.h.h.d.implementacion.DAOPedidoImpl - Pedido insertado con ID: 5
2025-02-28 20:53:24.551 [main] INFO  a.h.h.d.implementacion.DAOPedidoImpl - Pedido insertado con ID: 6
2025-02-28 20:53:24.557 [main] INFO  a.h.h.d.implementacion.DAOPedidoImpl - Pedido insertado con ID: 7
2025-02-28 20:53:24.561 [main] INFO  a.h.h.d.implementacion.DAOPedidoImpl - Pedido insertado con ID: 8
2025-02-28 20:53:24.566 [main] INFO  ad.hibernate.hmarort.ui.UIAutoImpl - ✓ Pedidos generados
2025-02-28 20:53:24.566 [main] INFO  ad.hibernate.hmarort.ui.UIAutoImpl - [INFORME AUTOMÁTICO]
2025-02-28 20:53:24.928 [main] ERROR a.h.h.d.i.DAOClienteImpl - Error al calcular la facturación del cliente
java.lang.IllegalStateException: org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl@1c459c28 is closed
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.errorIfClosed(AbstractLogicalConnectionImplementor.java:37)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:142)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:273)
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:121)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactionCoordinatorImpl.java:290)
	at org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:142)
	at ad.hibernate.hmarort.utils.SessionManager.executeWithResult(SessionManager.java:84)
	at ad.hibernate.hmarort.dao.implementacion.DAOClienteImpl.calcularFacturacionTotalCliente(DAOClienteImpl.java:128)
	at ad.hibernate.hmarort.ui.UIAutoImpl.generarInformesAutomaticos(UIAutoImpl.java:115)
	at ad.hibernate.hmarort.ui.UIAutoImpl.iniciar(UIAutoImpl.java:61)
	at ad.hibernate.hmarort.Main.main(Main.java:42)
2025-02-28 20:53:24.931 [main] ERROR ad.hibernate.hmarort.ui.UIAutoImpl - Error en la ejecución automática
java.sql.SQLException: Error al calcular la facturación: org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl@1c459c28 is closed
	at ad.hibernate.hmarort.dao.implementacion.DAOClienteImpl.calcularFacturacionTotalCliente(DAOClienteImpl.java:137)
	at ad.hibernate.hmarort.ui.UIAutoImpl.generarInformesAutomaticos(UIAutoImpl.java:115)
	at ad.hibernate.hmarort.ui.UIAutoImpl.iniciar(UIAutoImpl.java:61)
	at ad.hibernate.hmarort.Main.main(Main.java:42)
Caused by: java.lang.IllegalStateException: org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl@1c459c28 is closed
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.errorIfClosed(AbstractLogicalConnectionImplementor.java:37)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:142)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:273)
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:121)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactionCoordinatorImpl.java:290)
	at org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:142)
	at ad.hibernate.hmarort.utils.SessionManager.executeWithResult(SessionManager.java:84)
	at ad.hibernate.hmarort.dao.implementacion.DAOClienteImpl.calcularFacturacionTotalCliente(DAOClienteImpl.java:128)
	... 3 common frames omitted
2025-02-28 20:53:24.931 [main] ERROR ad.hibernate.hmarort.ui.UIAutoImpl - Error en proceso automático: Error al calcular la facturación: org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl@1c459c28 is closed
2025-02-28 20:53:24.931 [main] INFO  ad.hibernate.hmarort.Main - Aplicación finalizada exitosamente
